First attempt at working LH configuration.
"nix develop" builds, but:

caval build liquid-haskell gives me:

[1 of 1] Compiling Intro            ( Intro.hs, /Users/sperber/data/active-group/schulung/isaqb/formal-methods/fm-ag/dist-newstyle/build/aarch64-osx/ghc-9.12.2/liquid-haskell-0.1.0.0/build/Intro.o, /Users/sperber/data/active-group/schulung/isaqb/formal-methods/fm-ag/dist-newstyle/build/aarch64-osx/ghc-9.12.2/liquid-haskell-0.1.0.0/build/Intro.dyn_o ) [Source file changed]
Intro.hs:3:11: error:
    Illegal type specification for `Intro.i2`
    Intro.i2 :: {i : GHC.Types.Int | i >= 3}
    Sort Error in Refinement: {i : GHC.Types.Int | i >= 3}
    The sort GHC.Types.Int is not numeric
  because
The sort GHC.Types.Int is not numeric
    Just
  |
3 | {-@ i2 :: { i : Int | i >= 3 } @-}
  |           ^^^^^^^^^^^^^^^^^^^^^

Intro.hs:7:11: error:
    Illegal type specification for `Intro.i3`
    Intro.i3 :: {i : GHC.Types.Int | i >= 3}
    Sort Error in Refinement: {i : GHC.Types.Int | i >= 3}
    The sort GHC.Types.Int is not numeric
  because
The sort GHC.Types.Int is not numeric
    Just
  |
7 | {-@ i3 :: { i : Int | i >= 3 } @-}
  |           ^^^^^^^^^^^^^^^^^^^^^